FROM node:alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/

RUN apk add --update \
    python \
    python-dev \
    py-pip \
    build-base

RUN npm install

# Bundle app source
COPY laravel-echo-server.json /usr/src/app/laravel-echo-server.json
COPY domain.crt /usr/src/app/domain.crt
COPY domain.key /usr/src/app/domain.key

EXPOSE 3000
CMD [ "npm", "start" ]
